--------------------------------------------------------
--  Fichier créé - mardi-janvier-05-2021   
--------------------------------------------------------
DROP TABLE "ABIR"."COMMANDE";
DROP TABLE "ABIR"."CONGE";
DROP TABLE "ABIR"."EMPLOYE";
DROP TABLE "ABIR"."EVENEMENT";
DROP TABLE "ABIR"."FOURNISSEUR";
DROP TABLE "ABIR"."INVITE";
DROP TABLE "ABIR"."MARCHANDISE";
DROP TABLE "ABIR"."PACK";
DROP TABLE "ABIR"."RESERVATION";
DROP TABLE "ABIR"."SALLE";
DROP TABLE "ABIR"."SERVICE";
DROP TABLE "ABIR"."TABLE_EVENT";
--------------------------------------------------------
--  DDL for Sequence S_INVITE
--------------------------------------------------------

   CREATE SEQUENCE  "ABIR"."S_INVITE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 10 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence S_TABLE_EVENT
--------------------------------------------------------

   CREATE SEQUENCE  "ABIR"."S_TABLE_EVENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 10 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "ABIR"."COMMANDE" 
   (	"ID" NUMBER, 
	"NUMERO" NUMBER, 
	"QUANTITE" NUMBER, 
	"PRODUIT" VARCHAR2(20 BYTE), 
	"PRIX_TOTAL" FLOAT(126), 
	"DATED" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONGE
--------------------------------------------------------

  CREATE TABLE "ABIR"."CONGE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"DEBUT" VARCHAR2(20 BYTE), 
	"FIN" VARCHAR2(20 BYTE), 
	"IDEMP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "ABIR"."EMPLOYE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"FONCTION" VARCHAR2(20 BYTE), 
	"SCORE" NUMBER DEFAULT 0, 
	"MDP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENEMENT
--------------------------------------------------------

  CREATE TABLE "ABIR"."EVENEMENT" 
   (	"IDEVENEMENT" VARCHAR2(20 BYTE), 
	"NOMEVENEMENT" VARCHAR2(20 BYTE), 
	"TYPEEVENEMENT" VARCHAR2(20 BYTE), 
	"PRIXEVENEMENT" VARCHAR2(20 BYTE), 
	"TEMPSEVENEMENT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "ABIR"."FOURNISSEUR" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"NUM_TELEPHONE" NUMBER, 
	"EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INVITE
--------------------------------------------------------

  CREATE TABLE "ABIR"."INVITE" 
   (	"ID" NUMBER, 
	"NOM_INVITE" VARCHAR2(20 BYTE), 
	"PRENOM_INVITE" VARCHAR2(20 BYTE), 
	"TEL_INVITE" VARCHAR2(20 BYTE), 
	"EMAIL_INVITE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MARCHANDISE
--------------------------------------------------------

  CREATE TABLE "ABIR"."MARCHANDISE" 
   (	"TYPE" VARCHAR2(20 BYTE), 
	"QUANTITE" NUMBER, 
	"PRIX" FLOAT(126), 
	"NUMERO" NUMBER, 
	"PRODUIT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PACK
--------------------------------------------------------

  CREATE TABLE "ABIR"."PACK" 
   (	"IDPACK" VARCHAR2(20 BYTE), 
	"NOMPACK" VARCHAR2(20 BYTE), 
	"TYPEPACK" VARCHAR2(20 BYTE), 
	"IDEVE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "ABIR"."RESERVATION" 
   (	"ID" NUMBER, 
	"NOM_CLIENT" VARCHAR2(20 BYTE), 
	"PRENOM_CLIENT" VARCHAR2(20 BYTE), 
	"NOM_SALLE" VARCHAR2(20 BYTE), 
	"DATE_RESERVATION" VARCHAR2(20 BYTE), 
	"NB_HEURE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SALLE
--------------------------------------------------------

  CREATE TABLE "ABIR"."SALLE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"LIEU" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICE
--------------------------------------------------------

  CREATE TABLE "ABIR"."SERVICE" 
   (	"IDSERVICE" VARCHAR2(20 BYTE), 
	"NOMSERVICE" VARCHAR2(20 BYTE), 
	"CATHSERVICE" VARCHAR2(20 BYTE), 
	"PRIXSERVICE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TABLE_EVENT
--------------------------------------------------------

  CREATE TABLE "ABIR"."TABLE_EVENT" 
   (	"ID_TABLE" NUMBER, 
	"NOM_TABLE" VARCHAR2(20 BYTE), 
	"TYPE_TABLE" VARCHAR2(20 BYTE), 
	"NOMBRE_PLACE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ABIR.COMMANDE
SET DEFINE OFF;
Insert into ABIR.COMMANDE (ID,NUMERO,QUANTITE,PRODUIT,PRIX_TOTAL,DATED) values (9562,101010,14,'bbbb',11,'04/01/2020');
Insert into ABIR.COMMANDE (ID,NUMERO,QUANTITE,PRODUIT,PRIX_TOTAL,DATED) values (1234,1111,14,'amen',11,'04/01/2020');
REM INSERTING into ABIR.CONGE
SET DEFINE OFF;
Insert into ABIR.CONGE (ID,TYPE,DEBUT,FIN,IDEMP) values ('789','Maladie','01.01.2000','01.01.2000','55622768');
Insert into ABIR.CONGE (ID,TYPE,DEBUT,FIN,IDEMP) values ('189','Maladie','01.01.2000','01.01.2000','55622768');
Insert into ABIR.CONGE (ID,TYPE,DEBUT,FIN,IDEMP) values ('0','Maladie','01.01.2000','01.01.2000','55622768');
REM INSERTING into ABIR.EMPLOYE
SET DEFINE OFF;
Insert into ABIR.EMPLOYE (ID,NOM,PRENOM,EMAIL,FONCTION,SCORE,MDP) values ('55622768','Abir','Ayari','abirayari@esprit.tn','clients',15,'EMP-RH-55622768');
REM INSERTING into ABIR.EVENEMENT
SET DEFINE OFF;
Insert into ABIR.EVENEMENT (IDEVENEMENT,NOMEVENEMENT,TYPEEVENEMENT,PRIXEVENEMENT,TEMPSEVENEMENT) values ('416546','bjkbblj','Mariage','6456','687896');
REM INSERTING into ABIR.FOURNISSEUR
SET DEFINE OFF;
Insert into ABIR.FOURNISSEUR (ID,NOM,PRENOM,NUM_TELEPHONE,EMAIL) values (1111,'bddgscv','sdqf',184684,'amenallah.benkhalifa@esprit.tn');
Insert into ABIR.FOURNISSEUR (ID,NOM,PRENOM,NUM_TELEPHONE,EMAIL) values (1234,'fegves','fev',133435,'amenallah.benkhalifa@esprit.tn');
Insert into ABIR.FOURNISSEUR (ID,NOM,PRENOM,NUM_TELEPHONE,EMAIL) values (123456,'dddd','cds',99999,'amenallah.benkhalifa@esprit.tn');
Insert into ABIR.FOURNISSEUR (ID,NOM,PRENOM,NUM_TELEPHONE,EMAIL) values (90666,'aa','gg',2222,'amenallah.benkhalifa@esprit.tn');
Insert into ABIR.FOURNISSEUR (ID,NOM,PRENOM,NUM_TELEPHONE,EMAIL) values (1234,'dddd','cds',715545,'amenallah.benkhalifa@esprit.tn');
Insert into ABIR.FOURNISSEUR (ID,NOM,PRENOM,NUM_TELEPHONE,EMAIL) values (456666,'kljp','mmmmmmm',222222222,'amen@esprit.tn');
REM INSERTING into ABIR.INVITE
SET DEFINE OFF;
Insert into ABIR.INVITE (ID,NOM_INVITE,PRENOM_INVITE,TEL_INVITE,EMAIL_INVITE) values (1,'NGUE TOUGOUM','EMMNANUEL','52739385','ngue@gmail.com');
REM INSERTING into ABIR.MARCHANDISE
SET DEFINE OFF;
Insert into ABIR.MARCHANDISE (TYPE,QUANTITE,PRIX,NUMERO,PRODUIT) values ('amen123',19,19,19,'bbbbbb');
Insert into ABIR.MARCHANDISE (TYPE,QUANTITE,PRIX,NUMERO,PRODUIT) values ('amen123456',10,16.5,101010,'amen');
Insert into ABIR.MARCHANDISE (TYPE,QUANTITE,PRIX,NUMERO,PRODUIT) values ('amenamen',20,10.5,9999,'hhhh');
Insert into ABIR.MARCHANDISE (TYPE,QUANTITE,PRIX,NUMERO,PRODUIT) values ('mmmm',20,13.6,55113,'nnnn');
Insert into ABIR.MARCHANDISE (TYPE,QUANTITE,PRIX,NUMERO,PRODUIT) values ('ppp',20,13.6,55113,'nnnn');
REM INSERTING into ABIR.PACK
SET DEFINE OFF;
Insert into ABIR.PACK (IDPACK,NOMPACK,TYPEPACK,IDEVE) values ('45648648','lnepojgÃªz','Mariage','416546');
REM INSERTING into ABIR.RESERVATION
SET DEFINE OFF;
REM INSERTING into ABIR.SALLE
SET DEFINE OFF;
Insert into ABIR.SALLE (ID,NOM,TYPE,LIEU) values (151,'DFGDF','REGREG','ZFZRGF');
REM INSERTING into ABIR.SERVICE
SET DEFINE OFF;
Insert into ABIR.SERVICE (IDSERVICE,NOMSERVICE,CATHSERVICE,PRIXSERVICE) values ('787765','dklvsdk','mlfsmlsdd','846');
REM INSERTING into ABIR.TABLE_EVENT
SET DEFINE OFF;
Insert into ABIR.TABLE_EVENT (ID_TABLE,NOM_TABLE,TYPE_TABLE,NOMBRE_PLACE) values (1,'ALGERIE','Couple','2');
--------------------------------------------------------
--  DDL for Index IDC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABIR"."IDC_PK" ON "ABIR"."CONGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABIR"."EMPLOYE_PK" ON "ABIR"."EMPLOYE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index INVITE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABIR"."INVITE_PK" ON "ABIR"."INVITE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESERVATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABIR"."RESERVATION_PK" ON "ABIR"."RESERVATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SALLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABIR"."SALLE_PK" ON "ABIR"."SALLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE_EVENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABIR"."TABLE_EVENT_PK" ON "ABIR"."TABLE_EVENT" ("ID_TABLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger T_INVITE_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ABIR"."T_INVITE_ID" 
  BEFORE INSERT ON INVITE
  FOR EACH ROW
BEGIN
  SELECT S_INVITE.nextval
  INTO :new.id
  FROM dual;
END;
/
ALTER TRIGGER "ABIR"."T_INVITE_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_TABLE_EVENT_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ABIR"."T_TABLE_EVENT_ID" 
  BEFORE INSERT ON TABLE_EVENT
  FOR EACH ROW
BEGIN
  SELECT S_TABLE_EVENT.nextval
  INTO :new.id_table
  FROM dual;
END;

/
ALTER TRIGGER "ABIR"."T_TABLE_EVENT_ID" ENABLE;
--------------------------------------------------------
--  DDL for Synonymn DUAL
--------------------------------------------------------

  CREATE OR REPLACE PUBLIC SYNONYM "DUAL" FOR "SYS"."DUAL";
--------------------------------------------------------
--  Constraints for Table CONGE
--------------------------------------------------------

  ALTER TABLE "ABIR"."CONGE" ADD CONSTRAINT "IDC_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "ABIR"."EMPLOYE" MODIFY ("MDP" NOT NULL ENABLE);
  ALTER TABLE "ABIR"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_CHK1" CHECK (EMAIL like '%@%.%') ENABLE;
  ALTER TABLE "ABIR"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABIR"."EMPLOYE" MODIFY ("FONCTION" NOT NULL ENABLE);
  ALTER TABLE "ABIR"."EMPLOYE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ABIR"."EMPLOYE" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "ABIR"."EMPLOYE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ABIR"."EMPLOYE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVITE
--------------------------------------------------------

  ALTER TABLE "ABIR"."INVITE" ADD CONSTRAINT "INVITE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABIR"."INVITE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "ABIR"."RESERVATION" ADD CONSTRAINT "RESERVATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABIR"."RESERVATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SALLE
--------------------------------------------------------

  ALTER TABLE "ABIR"."SALLE" ADD CONSTRAINT "SALLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABIR"."SALLE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TABLE_EVENT
--------------------------------------------------------

  ALTER TABLE "ABIR"."TABLE_EVENT" ADD CONSTRAINT "TABLE_EVENT_PK" PRIMARY KEY ("ID_TABLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABIR"."TABLE_EVENT" MODIFY ("ID_TABLE" NOT NULL ENABLE);
